services:
  # Backend
  smart-brain-api:
    container_name: backend
    build: ./
    working_dir: /app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db-postgres
      REDIS_URI: ${REDIS_URI}
      # - REDIS_URI: redis://redis:6379
    depends_on:
      - db-postgres
      # - db-redis
    ports:
      - "3000:3000"
    command: npm start

  db-postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  # db-redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
