services:
  # Backend
  smart-brain-api:
    container_name: backend
    build: ./
    working_dir: /app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql13013
      POSTGRES_DB: smart_brain_docker
      POSTGRES_HOST: postgres
      REDIS_URI: rediss://default:AdC6AAIncDExMjMyOTFiYThmMzM0NmZkYmFiNTBlYzVhZmZhZWMxZHAxNTM0MzQ@many-amoeba-53434.upstash.io:6379
      # - REDIS_URI: redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    command: npm start

  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql13013*
      POSTGRES_DB: smart_brain_docker
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
